version: '3.1'
services:
    webserver:
        image: 'nginx:alpine'
        working_dir: /var/www/public
        volumes:
            - './src:/var/www/public'
            - './docker-data/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
            - './logs/nginx:/var/log/nginx'
        ports:
            - '3000:80'

    php-fpm:
        build: docker-data/php-fpm
        working_dir: /var/www/public
        volumes:
            - './src:/var/www/public'
            - './docker-data/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini'
            - './docker-data/php-fpm/openssl.cnf:/etc/ssl/openssl.cnf'
        command: php-fpm -R
